project:
  type: website
  output-dir: docs

website:
  title: "Joshua Ferrer-Lozano"
  #favicon: #image/"pic_name"
  navbar:
    title: false
    left:
    #logo: #images/logo.png
    #logo-alt: #description of the image
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Personal Life
    menu:
      - href: resources.qmd
        text: Resources
      - href: blog.qmd
        text: Blog
      - href: photo_gallery.qmd
        text: The World Through Film

format:
  html:
    theme: none
    css: styles.scss
    toc: true
    page-layout: full
    mainfont: Nunito


page-footer:
  left: Copyright 2025, Joshua Ferrer-Lozano
  right:
    - icon: Github
