project:
  type: website
  output-dir: docs

website:
  title: "Joshua Ferrer-Lozano"   # <-- site title
  #site-url: 
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: photo_gallery.qmd
        text: The World Through Film
      - href: blog_page.qmd
        text: Blog
        menu: 
          - icon: linkedin
            text: LinkedIn
            href: https://www.linkedin.com/in/joshuarflozano/
            target: _blank
          - icon: github
            text: GitHub
            href: https://github.com/Awoo56709
            target: _blank
          - text: Email
            href: "mailto:joshuar.f.lozano@gmail.com"
            
collections:
  posts:
    categories: true
    sort: "date desc"


#format:
 # html:
  #  css: site_css.css   # or styles.css
