project:
  type: website
  output-dir: docs

website:
  title: "Joshua Ferrer-Lozano"
  site-url: https://awoo56709.github.io/
  navbar:
    title: false
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Biography
      - href: photo_gallery.qmd
        text: The World Through Film
      - href: blog.qmd
        text: Blog
      - text: Get in Touch!
        menu: 
          - icon: linkedin
            text: LinkedIn
            href: https://www.linkedin.com/in/joshuarflozano/
            target: _blank
          - icon: github
            text: GitHub
            href: https://github.com/Awoo56709
            target: _blank
          - text: Email
            href: "mailto:joshuar.f.lozano@gmail.com"

page-footer:
  left: Copyright 2025, Joshua Ferrer-Lozano
  right:
    - icon: Github

format:
  html:
    theme: none
    css: styles.scss
    toc: true
    page-layout: full
    mainfont: Nunito
