project:
  type: website
  output-dir: docs

website:
  title: "Joshua Ferrer-Lozano"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - text: The World Through Film
        menu:
          - href: photo_gallery.qmd
            text: General Gallery
          - href: armenia.qmd
            text: Armenia
          - href: italy.qmd
            text: Italia
          - href: turkiye.qmd
            text: Turkiye
          - href: recuerdos.qmd
            text: Recuerdos
          - href: peace_corps.qmd
            text: მშვისდობის კორპუსი
      - href: blog_page.qmd
        text: Blog
      - href: /files/resume.pdf
        text: Resume
        target: _blank

collections:
  posts:
    categories: true
    sort: "date desc"
