project:
  type: website
  output-dir: docs

website:
  title: "Joshua Ferrer-Lozano"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - text: The World Through Film
        menu:
          - href: photo_gallery.qmd
            text: General Gallery
          - href: peace_corps.qmd
            text: Peace Corps Service
          - href: armenia_travel.qmd
            text: Travel to Armenia
          - href: professional.qmd
            text: In the Field
      - text: Blog
        menu:
          - href: blog_page.qmd
            text: Blog Home
          - href: https://www.linkedin.com/in/joshuarflozano/
            text: LinkedIn
            target: _blank
          - href: https://github.com/Awoo56709
            text: GitHub
            target: _blank
          - href: "mailto:joshuar.f.lozano@gmail.com"
            text: Email

collections:
  posts:
    categories: true
    sort: "date desc"