project:
  type: website
  output-dir: docs

website:
  title: "Joshua Ferrer-Lozano"   # <-- site title
  site-url: https://awoo56709.github.io/
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: photo_gallery.qmd
        text: The World Through Film
      - href: blog.qmd
        text: Blog
      - text: Get in Touch!
        menu: 
          - icon: linkedin
            text: LinkedIn
            href: https://www.linkedin.com/in/joshuarflozano/
            target: _blank
          - icon: github
            text: GitHub
            href: https://github.com/Awoo56709
            target: _blank
          - text: Email
            href: "mailto:joshuar.f.lozano@gmail.com"
